### PR TITLE
Cleanup project files

### PR DESCRIPTION
**Pull request by Joe-Joe-Joe-Joe**
guess who got distracted

### CODE REVIEW

**Comment by FinnBreu** [comment]
Why not merge into main?

**Comment by FinnBreu** [comment]
Why merge into main

**Comment by FinnBreu** [comment]
And why is borealis.mlx in scripts, and not in the top level next to the simulation.slx? Need to run that at startup

**Comment by sqfewqlk** [comment]
im assuming nothing is wrong with this. there is some other more nitty gritty clean up that needs to be done too (some of the stuff in the forcing blocks is just really ugly and needs to be fixed). once were on break and have the control system etc. implemented im willing to pull a branch and just tidy stuff up.

**Comment by Joe-Joe-Joe-Joe** [comment]
> Why not merge into main?

Cause you would then have to rebase main onto your branch and that's annoying

**Comment by Jacob-Lin-04** [comment]
I agree that the readme should be updated. Possibly a quick start guide to how to run the sim? 
We could also go through and update variables and files names to be fully in English to avoid confusion.

**Pull request merged**
