### PR TITLE
J lin

### PR DESCRIPTION
**Pull request by Jacob-Lin-04**
I have added OR_cg as a 1d T(U) lookup table in barrowman.mat. Incorporated in place of x_cg constant variable. Can confirm it runs and compiles but should double check if it is having the expected effect on the rocket model. Seems that the comparison plots are closer together than before. 

OR_comp_alt
OR_comp_pitch

### CODE REVIEW

**Comment by Joe-Joe-Joe-Joe** [comment]
This is what the old pitch looks like
image

**Comment by Joe-Joe-Joe-Joe** [comment]
This is what I get running the scripts then the model
image
Did you actually put it in the `.mat` file manually? cause that's not the place to add it
You should define it with all the other series in Borealis.mlx
(can't do inline comments unfortunately since Matlab sucks like that)
image

**Comment by Jacob-Lin-04** [comment]
I put the or_cg into the mat file manually yes. It compiles for me when I manually click on the .mat file

**Comment by Jacob-Lin-04** [comment]
Implemented the time series in the proper place. Plots seem to have not changed
OR_comp_alt(mlx)
Or_comp_pitch(mlx)

**Pull request merged**
